float32 IGNORE_DISTANCE =0.0
uint8 PROCESSING_NEW_GOAL =1

# Define the action request
string[] landmark_types
float32  distance

---
# Define the action result
uint8 result
---
# Define the action feedback
vortex_msgs/OdometryArray feedback

