# Goal
vortex_msgs/Waypoint[] waypoints
float64 switching_threshold
---
# Result
geometry_msgs/Pose final_pose
bool success
uint32 completed_waypoints
---
# Feedback
geometry_msgs/Pose current_pose
uint32 current_waypoint_index
float64 distance_to_waypoint
