# Goal
vortex_msgs/Waypoint[] waypoints
float64 convergence_threshold
bool persistent # Action is not terminated when waypoints are reached. Can only be stopped through cancellation from client.
---
# Result
geometry_msgs/Pose final_pose
bool pose_valid
bool success
---
# Feedback
geometry_msgs/Pose current_pose
vortex_msgs/Waypoint current_waypoint
