#request
vortex_msgs/Waypoint[] waypoints
float64 switching_threshold
bool overwrite # Deletes all prior waypoints in queue.
bool priority # If true, rejects all new non-priority waypoints while executing.
---
#response
bool success
